src/main/java/umc/demoday/whatisthis/global/config/SecurityConfig.java

Close #13 
- SecurityConfig에 SecurityFilterChain 엔드포인트 수정해서 이메일 인증코드 오류 해결

Fix/13 fix SecurityConfig 수정

---

src/main/java/umc/demoday/whatisthis/domain/member/Member.java
src/main/java/umc/demoday/whatisthis/domain/member/service/member/MemberAuthServiceImpl.java

Close #32 
- Member 엔티티에 lastLoginAt 필드추가
- 로그인 기록 남기는 로직 추가

Feat/32 feat 로그인 기록 남기기 구현

---

src/main/java/umc/demoday/whatisthis/WhatisthisApplication.java
src/main/java/umc/demoday/whatisthis/domain/hashtag/repository/HashtagRepository.java
src/main/java/umc/demoday/whatisthis/domain/post/controller/PostController.java
src/main/java/umc/demoday/whatisthis/domain/post/converter/PostConverter.java
src/main/java/umc/demoday/whatisthis/domain/post/dto/PostRequestDTO.java
src/main/java/umc/demoday/whatisthis/domain/post/dto/PostResponseDTO.java
src/main/java/umc/demoday/whatisthis/domain/post/enums/Category.java
src/main/java/umc/demoday/whatisthis/domain/post/repository/PostRepository.java
src/main/java/umc/demoday/whatisthis/domain/post/service/PostService.java
src/main/java/umc/demoday/whatisthis/domain/post/service/PostServiceImpl.java
src/main/java/umc/demoday/whatisthis/domain/post_image/repository/PostImageRepository.java
src/main/java/umc/demoday/whatisthis/domain/post_scrap/repository/PostScrapRepository.java
src/main/java/umc/demoday/whatisthis/global/config/JpaAuditingConfiguration.java
src/test/java/umc/demoday/whatisthis/domain/member/service/email/EmailAuthServiceImplTest.java
src/test/java/umc/demoday/whatisthis/domain/member/service/member/MemberCommandServiceImplTest.java
src/test/java/umc/demoday/whatisthis/domain/post/controller/PostControllerTest.java
src/test/java/umc/demoday/whatisthis/domain/post/service/PostServiceImplTest.java

Close #19 
- [Feat] 생활꿀팁, 생활꿀템 개별 게시글 조회 API

[Feat] 생활꿀팁, 생활꿀템 개별 게시글 조회 API

---

src/main/java/umc/demoday/whatisthis/domain/post/controller/PostController.java
src/main/java/umc/demoday/whatisthis/domain/post/service/PostService.java
src/main/java/umc/demoday/whatisthis/domain/post/service/PostServiceImpl.java
src/main/java/umc/demoday/whatisthis/domain/post_scrap/PostScrap.java
src/main/java/umc/demoday/whatisthis/global/CustomUserDetails.java
src/test/java/umc/demoday/whatisthis/domain/post/service/PostServiceImplTest.java

Close #44 
- feat : 게시물 스크랩 API, TEST 완료

feat : 게시물 스크랩 API, TEST 완료

---

src/main/java/umc/demoday/whatisthis/domain/admin/controller/AdminPostController.java
src/main/java/umc/demoday/whatisthis/domain/admin/dto/AdminPostResDTO.java
src/main/java/umc/demoday/whatisthis/domain/admin/service/AdminPostService.java
src/test/java/umc/demoday/whatisthis/domain/admin/service/AdminPostServiceTest.java

Close #60 
- Feat/관리자페이지 게시글 조회
AdminPostController와 AdminPostService 클래스 생성. getPost 메소드 각각 구현

Feat/관리자페이지 게시글 조회

---

src/main/java/umc/demoday/whatisthis/domain/admin/controller/AdminPostController.java
src/main/java/umc/demoday/whatisthis/domain/admin/dto/AdminPostReqDTO.java
src/main/java/umc/demoday/whatisthis/domain/admin/dto/AdminPostResDTO.java
src/main/java/umc/demoday/whatisthis/domain/admin/service/AdminPostService.java
src/main/java/umc/demoday/whatisthis/domain/post_image/repository/PostImageRepository.java
src/test/java/umc/demoday/whatisthis/domain/admin/service/AdminPostServiceTest.java

Close #66  
- Feat/관리자페이지 게시글 등록 
AdminPostController와 AdminPostService 클래스에 createPost 메소드 구현

Feat/관리자페이지 게시글 등록

---

src/main/java/umc/demoday/whatisthis/domain/admin/controller/AdminPostController.java
src/main/java/umc/demoday/whatisthis/domain/admin/dto/AdminPostReqDTO.java
src/main/java/umc/demoday/whatisthis/domain/admin/dto/AdminPostResDTO.java
src/main/java/umc/demoday/whatisthis/domain/admin/service/AdminPostService.java
src/main/java/umc/demoday/whatisthis/domain/post_image/repository/PostImageRepository.java
src/test/java/umc/demoday/whatisthis/domain/admin/service/AdminPostServiceTest.java

Close #68 
- Feat/관리자페이지 게시글 목록 조회 API 구현 
AdminPostController와 AdminPostService 클래스에 getAllPost 메소드 구현
AdminPostResDTO에 구현에 필요한 DTO 작성

Feat/관리자페이지 게시글 목록 조회

---

src/main/java/umc/demoday/whatisthis/domain/member/Member.java
src/main/java/umc/demoday/whatisthis/domain/member/controller/MemberFindController.java
src/main/java/umc/demoday/whatisthis/domain/member/dto/member/PasswordChangeReqDTO.java
src/main/java/umc/demoday/whatisthis/domain/member/dto/member/PasswordResetReqDTO.java
src/main/java/umc/demoday/whatisthis/domain/member/dto/member/VerifyResetCodeReqDTO.java
src/main/java/umc/demoday/whatisthis/domain/member/repository/MemberRepository.java
src/main/java/umc/demoday/whatisthis/domain/member/service/email/PasswordResetService.java
src/main/java/umc/demoday/whatisthis/domain/member/service/email/PasswordResetServiceImpl.java
src/main/java/umc/demoday/whatisthis/global/apiPayload/code/GeneralErrorCode.java
src/main/java/umc/demoday/whatisthis/global/apiPayload/code/GeneralSuccessCode.java
src/main/java/umc/demoday/whatisthis/global/config/SecurityConfig.java

Close #55 
- 비밀번호 재설정 - 이메일 인증 코드 전송 api 구현
- 이메일 인증 코드 검증 api 구현
- 비밀번호 변경 api 구현

Feat/55 feat 비밀번호 재설정

---

src/main/java/umc/demoday/whatisthis/global/S3TestController.java

Close #84 
- 이미지 업로드 url 반환
- 스웨거에서 사용가능하게
6e255c63ef5477b2aa24d941f84d66284126a207

[Fix] 파일 업로드 테스트 컨트롤러 스웨거에서 사용 가능하게 수정

---

src/main/java/umc/demoday/whatisthis/global/S3TestController.java
src/main/java/umc/demoday/whatisthis/global/apiPayload/code/GeneralErrorCode.java

Close #86 
- 이미지 업로드 여러장 가능하게 수정
c14f453f7799e865f642e96249e02ac8c545852b
ecd4308bafbe926a48bb0edf15e050c5dacd6343

Feat/86 feat 이미지 업로드 여러장 가능하게 수정

---

src/main/java/umc/demoday/whatisthis/domain/inquiry/Inquiry.java
src/main/java/umc/demoday/whatisthis/domain/inquiry/controller/InquiryController.java
src/main/java/umc/demoday/whatisthis/domain/inquiry/converter/InquiryConverter.java
src/main/java/umc/demoday/whatisthis/domain/inquiry/dto/reqDTO/InquiryCreateReqDTO.java
src/main/java/umc/demoday/whatisthis/domain/inquiry/service/InquiryCommandService.java
src/main/java/umc/demoday/whatisthis/domain/inquiry/service/InquiryCommandServiceImpl.java

- [] 버그 수정
Close #101 
- 문의 등록
0b9738eac1d24cb7fa7b9cd451f349d7d019aae2
10e78e2a7d37d94ed715dea544c4940a848c3643

Feat/101 feat 문의 등록

---

src/main/java/umc/demoday/whatisthis/domain/inquiry/code/InquiryErrorCode.java
src/main/java/umc/demoday/whatisthis/domain/inquiry/controller/AdminInquiryController.java
src/main/java/umc/demoday/whatisthis/domain/inquiry/controller/InquiryController.java
src/main/java/umc/demoday/whatisthis/domain/inquiry/service/InquiryQueryService.java
src/main/java/umc/demoday/whatisthis/domain/inquiry/service/InquiryQueryServiceImpl.java
src/main/java/umc/demoday/whatisthis/global/config/SecurityConfig.java

Close #106 
- 문의내역 상세조회
58258fee5e5b69c789e2f805fc5c47a368100e7a

[Feat] 문의내역 상세조회

---

src/main/java/umc/demoday/whatisthis/domain/post/controller/PostController.java
src/main/java/umc/demoday/whatisthis/domain/post/service/PostService.java
src/main/java/umc/demoday/whatisthis/domain/post/service/PostServiceImpl.java
src/main/java/umc/demoday/whatisthis/global/security/JwtAuthenticationFilter.java
src/test/java/umc/demoday/whatisthis/domain/post/controller/PostControllerTest.java

Close #
- AthenticationFilter 바꾸니 기존 코드에 문제 발생해서 원상 복귀 후 그에 따라서 게시물 추천 AI 수정
JwtAthenticationFilter.class
PostServiceImpl.class

[Fix] AthenticationFilter 원상복귀 및 그에 따른 게시물 추천 ai 수정

---

src/main/java/umc/demoday/whatisthis/domain/post/controller/PostController.java
src/main/java/umc/demoday/whatisthis/domain/post/converter/PageConverter.java
src/main/java/umc/demoday/whatisthis/domain/post/repository/PostRepository.java
src/main/java/umc/demoday/whatisthis/domain/post/service/PostServiceImpl.java
src/main/java/umc/demoday/whatisthis/global/config/SecurityConfig.java

Close #119 
- 생활페이지 전체 조회 API 수정 
- SecurityConfig에서 /post/** 접근 권한 수정
src/main/java/umc/demoday/whatisthis/domain/post/converter/PageConverter.java
src/main/java/umc/demoday/whatisthis/domain/post/controller/PostController.java
src/main/java/umc/demoday/whatisthis/domain/post/service/PostServiceImpl.java
src/main/java/umc/demoday/whatisthis/global/config/SecurityConfig.java
src/main/java/umc/demoday/whatisthis/domain/post/repository/PostRepository.java

Fix/생활페이지 전체 조회 및 security chain

---

src/main/java/umc/demoday/whatisthis/domain/post_scrap/PostScrap.java
src/main/java/umc/demoday/whatisthis/domain/post_scrap/controller/PostScrapController.java
src/main/java/umc/demoday/whatisthis/domain/post_scrap/converter/MyScrapPageConverter.java
src/main/java/umc/demoday/whatisthis/domain/post_scrap/dto/resDTO/MyScrapPageResDTO.java
src/main/java/umc/demoday/whatisthis/domain/post_scrap/dto/resDTO/MyScrapSummaryResDTO.java
src/main/java/umc/demoday/whatisthis/domain/post_scrap/repository/PostScrapRepository.java
src/main/java/umc/demoday/whatisthis/domain/post_scrap/service/PostScrapQueryService.java
src/main/java/umc/demoday/whatisthis/domain/post_scrap/service/PostScrapQueryServiceImpl.java

Close #118 
- 스크랩페이지
7e351b321b4cb8ef2401abe1539037c72e452b61
31578b8e52965bd48e93fdc26e7cd97ffa28ff47

Feat/118 feat 스크랩페이지

---

src/main/java/umc/demoday/whatisthis/domain/admin/service/AdminPostService.java

Close #128 
-  꿀팁 꿀템 삭제, 업데이트 문제 해결 완료
문제 원인 : 벡터DB에 게시물을 저장하는 특정 메소드에 문제 발생.

Fix : 꿀팁 꿀템 삭제, 업데이트 문제 해결 완료

---

src/main/java/umc/demoday/whatisthis/domain/post_scrap/dto/resDTO/MyScrapSummaryResDTO.java

Close #134 
- DTO 수정
- authorName 제외
- viewCount 추가
1ab90a23fcbeb6b12f460d4718fab93a116e446e

[Fix] ScrapResDto 수정

---

src/main/java/umc/demoday/whatisthis/global/config/SecurityConfig.java

Close #137 
- CorsCOnfigurationSource AllowedMethod 수정
src/main/java/umc/demoday/whatisthis/global/config/SecurityConfig.java

 Fix : CorsCOnfigurationSource AllowedMethod 수정

---

src/main/java/umc/demoday/whatisthis/domain/post_scrap/dto/resDTO/MyScrapSummaryResDTO.java

Close #136 
- 스크랩 DTO 수정
7473a04b125c45b4852a94f020345f61610c6c1d

[Fix] 스크랩 DTO 수정

---

src/main/java/umc/demoday/whatisthis/global/config/SecurityConfig.java

[Fix]비로그인 유저도 게시물 조회 가능하게 수정

---

src/main/java/umc/demoday/whatisthis/domain/member/service/member/MemberAuthServiceImpl.java
src/main/java/umc/demoday/whatisthis/domain/post/service/PostService.java
src/main/java/umc/demoday/whatisthis/domain/post_scrap/repository/PostScrapRepository.java
src/main/java/umc/demoday/whatisthis/global/config/SecurityConfig.java
src/main/java/umc/demoday/whatisthis/global/service/CustomUserDetailsService.java

Close #141 
- 로그인 방식을 CustomUserDetails 사용해서 하도록 변경

Bug/141 bug 로그인 방식 수정

---

src/main/java/umc/demoday/whatisthis/domain/inquiry/converter/MyPageInquiryConverter.java

[Fix] 프로필 이미지 nullable

---

src/main/java/umc/demoday/whatisthis/domain/admin/controller/AdminPostController.java
src/main/java/umc/demoday/whatisthis/domain/post/service/PostServiceImpl.java

Close #143 
- 로그인 하지 않아도 꿀팁 꿀템 포스트가 보이게 수정
src/main/java/umc/demoday/whatisthis/domain/post/service/PostServiceImpl.java
src/main/java/umc/demoday/whatisthis/domain/admin/controller/AdminPostController.java

Fix/비로그인 post 보이기

---

src/main/java/umc/demoday/whatisthis/domain/member/controller/MemberAuthController.java
src/main/java/umc/demoday/whatisthis/domain/member/service/member/MemberAuthService.java
src/main/java/umc/demoday/whatisthis/domain/member/service/member/MemberAuthServiceImpl.java
src/main/java/umc/demoday/whatisthis/global/config/SecurityConfig.java

Close #155 
- 로그아웃 구현
- refreshToken 단순 삭제하는 방식

Feat/155 feat 로그아웃

---

src/main/java/umc/demoday/whatisthis/domain/post_scrap/controller/PostScrapController.java
src/main/java/umc/demoday/whatisthis/domain/post_scrap/repository/PostScrapRepository.java
src/main/java/umc/demoday/whatisthis/domain/post_scrap/service/PostScrapQueryServiceImpl.java

Close #160 
- 쿼리 수정
d0070e297323bbc642d58d2a44ed867046073d63

[Fix] 스크랩 조회 가능하게 구현

---

src/main/java/umc/demoday/whatisthis/domain/post/controller/CommunityPostController.java

[Fix] 신고 API 설명 추가

---

src/main/java/umc/demoday/whatisthis/domain/admin/controller/AdminAuthController.java
src/main/java/umc/demoday/whatisthis/domain/admin/service/AdminAuthService.java
src/main/java/umc/demoday/whatisthis/domain/admin/service/AdminAuthServiceImpl.java
src/main/java/umc/demoday/whatisthis/domain/refresh_token/AdminRefreshToken.java
src/main/java/umc/demoday/whatisthis/domain/refresh_token/repository/AdminRefreshTokenRepository.java
src/main/java/umc/demoday/whatisthis/global/config/SecurityConfig.java

Close #159 
- 관리자 로그아웃 구현
- 단순 refreshToken 삭제 방식

Feat/159 feat 관리자 로그아웃

---

src/main/java/umc/demoday/whatisthis/domain/admin/service/AdminPostService.java
src/main/java/umc/demoday/whatisthis/domain/post/service/CommunityPostServiceImpl.java

[Fix] 엔티티 변경에 따른 글작성 API 수정

---

src/main/java/umc/demoday/whatisthis/domain/admin/controller/AdminAuthController.java
src/main/java/umc/demoday/whatisthis/domain/admin/service/AdminAuthService.java
src/main/java/umc/demoday/whatisthis/domain/admin/service/AdminAuthServiceImpl.java
src/main/java/umc/demoday/whatisthis/domain/member/controller/MemberAuthController.java
src/main/java/umc/demoday/whatisthis/domain/member/service/member/MemberAuthService.java
src/main/java/umc/demoday/whatisthis/domain/member/service/member/MemberAuthServiceImpl.java
src/main/java/umc/demoday/whatisthis/global/security/JwtProvider.java

Close #169 
- accessToken 블랙리스트로 차단해서 즉시 로그아웃 되게 변경

Feat/169 feat 멤버 관리자 로그아웃 시 accesstoken 차단

---

src/main/java/umc/demoday/whatisthis/domain/member/service/member/MemberCommandServiceImpl.java
src/main/java/umc/demoday/whatisthis/domain/profile_image/ProfileImage.java

Close #166 
- 프로필이미지 테이블에는 member_id가 안들어
3a5f30e52f14e7976127f47170b68bd25ab9ce8b
ad533b2ff573bea1190b584e718a13a3b05b09bb

Feat/166 feat 회원가입시 기본프로필 설정

---

src/main/java/umc/demoday/whatisthis/global/config/CorsConfig.java

Close #174 
- 도메인 cors 설정
548b68dcae7ed00cb620d84bdf3d8d1b3876bc06

[Chore] 도메인 cors 설정

---

src/main/java/umc/demoday/whatisthis/domain/post/service/PostServiceImpl.java

Close #175 
- Fix : ViewCount 증가 오류 수정

Fix : ViewCount 증가 오류 수정

---

src/main/java/umc/demoday/whatisthis/global/config/SecurityConfig.java
src/main/java/umc/demoday/whatisthis/global/security/JwtAuthenticationFilter.java

Close #184 
- cors 설정 변경
b524c961fc7168a7090445191d2fbb2f4a470adb

[Chore] cors 설정 변경

---

src/main/java/umc/demoday/whatisthis/global/config/SecurityConfig.java

[Fix] 고객센터 권한 수정

---

src/main/java/umc/demoday/whatisthis/domain/recommendation/RecommendationService.java

Close #196 
- Default AI 추천 메소드 수정
기준이 되는 게시물을 205번 게시물로 잡았습니다.

Refacto : Default AI 추천 메소드 수정

---

src/main/java/umc/demoday/whatisthis/domain/notice/controller/AdminNoticeController.java
src/main/java/umc/demoday/whatisthis/domain/notice/service/NoticeCommandService.java
src/main/java/umc/demoday/whatisthis/domain/notice/service/NoticeCommandServiceImpl.java
src/main/java/umc/demoday/whatisthis/domain/qna/controller/AdminQnaController.java
src/main/java/umc/demoday/whatisthis/domain/qna/service/QnaCommandService.java
src/main/java/umc/demoday/whatisthis/domain/qna/service/QnaCommandServiceImpl.java

Close #199 
- 공지사항, qna 작성 시 adminId를 CustomUserDetails로 넘어가게 해줌

Bug/199 bug 관리자 qna notice등 작성 오류

---

build.gradle
src/main/java/umc/demoday/whatisthis/WhatisthisApplication.java
src/main/java/umc/demoday/whatisthis/domain/admin/controller/AdminPostController.java
src/main/java/umc/demoday/whatisthis/domain/admin/redis/PostDocument.java
src/main/java/umc/demoday/whatisthis/domain/admin/redis/PostMapper.java
src/main/java/umc/demoday/whatisthis/domain/admin/redis/PostSearchRepository.java
src/main/java/umc/demoday/whatisthis/domain/admin/redis/SearchPostResponseDTO.java
src/main/java/umc/demoday/whatisthis/domain/admin/redis/async/AsyncConfig.java
src/main/java/umc/demoday/whatisthis/domain/admin/redis/async/InitialDataIndexer.java
src/main/java/umc/demoday/whatisthis/domain/admin/redis/async/PostEvent.java
src/main/java/umc/demoday/whatisthis/domain/admin/redis/async/SearchIndexingListener.java
src/main/java/umc/demoday/whatisthis/domain/admin/redis/search/SearchService.java
src/main/java/umc/demoday/whatisthis/domain/admin/service/AdminPostService.java
src/main/java/umc/demoday/whatisthis/domain/post/controller/PostController.java
src/main/java/umc/demoday/whatisthis/domain/post/converter/CategoryConverter.java
src/main/java/umc/demoday/whatisthis/domain/post/dto/IntegratedSearchResponseDTO.java
src/main/java/umc/demoday/whatisthis/domain/post/dto/SingleSearchDTO.java
src/main/java/umc/demoday/whatisthis/domain/post/service/CommunityPostServiceImpl.java
src/main/java/umc/demoday/whatisthis/domain/post/service/PostService.java
src/main/java/umc/demoday/whatisthis/domain/recommendation/RecommendationService.java
src/main/java/umc/demoday/whatisthis/global/config/RedisConfig.java

This reverts commit 3481cb488dda2004af0328efe76222e127bb6c68.
Close #145 
- 서버에 redis-pull-stack 설치해서 통합 검색 및 인기검색어 API 다시 PR 올립니다.
- 자세한 구현 방식은 이슈 #145번에 있습니다

Revert "Revert "Feat/redisearch를 이용한 통합 검색 구현""

---

src/main/java/umc/demoday/whatisthis/global/OAuth2SuccessHandler.java

Close #208 
- 프론트 콜백 주소를 고정해 4가지 상황을 고정해 보았다

[Fix] 프론트 콜백 주소 고정

---

src/main/java/umc/demoday/whatisthis/global/config/RedisConfig.java

 Fix : REDIS PASSWORD setting

---

src/main/java/umc/demoday/whatisthis/global/config/SecurityConfig.java

Close #214 
- cors 프론트 배포 도메인 추가

[Chore] cors 프론트 도메인 추가

---

src/main/java/umc/demoday/whatisthis/global/security/JwtAuthenticationFilter.java

[Fix] OPTIONS 단락 제거

---

src/main/java/umc/demoday/whatisthis/domain/member_profile/MemberActivityService.java
src/main/java/umc/demoday/whatisthis/domain/member_profile/MemberProfile.java
src/main/java/umc/demoday/whatisthis/domain/post/controller/PostController.java
src/main/java/umc/demoday/whatisthis/domain/post/service/PostServiceImpl.java
src/main/java/umc/demoday/whatisthis/domain/recommendation/RecommendationService.java

Close #231 
- Fix : 꿀템추천 수정 완료
Default Seed Post에 문제가 있었습니다

Fix : 꿀템추천 수정 완료

---

src/main/java/umc/demoday/whatisthis/domain/member/controller/MemberController.java
src/main/java/umc/demoday/whatisthis/global/OAuth2SuccessHandler.java
src/main/java/umc/demoday/whatisthis/global/config/SecurityConfig.java

Close #236 
- http로 로그인 요청 안가게 설정

[Fix] http로 요청 안가게 설정

---

src/main/java/umc/demoday/whatisthis/domain/member/controller/MemberController.java
src/main/java/umc/demoday/whatisthis/domain/member/dto/member/MemberResDTO.java
src/main/java/umc/demoday/whatisthis/domain/member/service/member/MemberCommandService.java
src/main/java/umc/demoday/whatisthis/domain/member/service/member/MemberCommandServiceImpl.java
src/main/java/umc/demoday/whatisthis/global/OAuth2SuccessHandler.java
src/main/java/umc/demoday/whatisthis/global/config/SecurityConfig.java
src/main/java/umc/demoday/whatisthis/global/security/JwtProvider.java
src/main/resources/application.yml

Close #240 
- 연동 linkToken으로 변경

[Fix] link-social 시 linkToken 붙음

---

src/main/java/umc/demoday/whatisthis/domain/member/controller/AuthBootstrapController.java
src/main/java/umc/demoday/whatisthis/domain/member/controller/MemberAuthController.java
src/main/java/umc/demoday/whatisthis/domain/member/controller/MemberController.java
src/main/java/umc/demoday/whatisthis/domain/member/service/member/MemberAuthService.java
src/main/java/umc/demoday/whatisthis/domain/member/service/member/MemberAuthServiceImpl.java
src/main/java/umc/demoday/whatisthis/global/config/SecurityConfig.java

Close #245 
- 로그아웃 시 소셜일 경우 쿠키 삭제

Bug/245 bug 소셜 로그아웃 쿠키 삭제

---

src/main/java/umc/demoday/whatisthis/domain/member/controller/MemberController.java
src/main/java/umc/demoday/whatisthis/domain/member/dto/member/SocialSignupReqDTO.java
src/main/java/umc/demoday/whatisthis/domain/member/service/member/MemberCommandService.java
src/main/java/umc/demoday/whatisthis/domain/member/service/member/MemberCommandServiceImpl.java
src/main/java/umc/demoday/whatisthis/global/OAuth2SuccessHandler.java
src/main/java/umc/demoday/whatisthis/global/security/JwtProvider.java

Bug/247 bug 소셜로그인 회원가입 에러

---

src/main/java/umc/demoday/whatisthis/global/config/SecurityConfig.java

[Chore] 오타 수정

---

src/main/java/umc/demoday/whatisthis/global/config/SecurityConfig.java

[Chore] 수정

---

src/main/java/umc/demoday/whatisthis/domain/member/service/member/MemberCommandServiceImpl.java
src/main/java/umc/demoday/whatisthis/global/apiPayload/code/GeneralErrorCode.java

[Fix] 회원가입 중복 이메일 방지

---

src/main/resources/application.yml

Close #271
- yml 파일에 timezone seoul 설정
297f9fc8a962f978b7596f2920df3e2189f65eec

[Fix] yml 파일에 timezone seoul 설정
